telegram:
  bot:
    token: 6977521869:AAHoom3w_K-3M_Y4Ladz0DftcMwfQG6UQYg
    username: t.me/my_search_books_bot


spring:
  datasource:
    url: jdbc:postgresql://localhost:1010/postgres
    username: postgres
    password: 1010
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect

